### PR TITLE
Enable golangci-lint in the unit testing phase, fix all the errors

### LINKED ISSUE #325: K8SSAND-1470 ⁃ Add static checking to unit tests in GHA
**What is missing?**
We do not have any staticchecking that verifies that PRs do not forget to check some basic stuff (such as errors returned by functions). Adding golangci-lint seems reasonable as its used in many projects (it bundles many different linters and allows to check which ones are ran).

**Why do we need it?**
staticchecks, if not too rigorous, can catch some easy-to-miss bugs.

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    **Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1470) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1470
┆priority: Medium

### PR DESCRIPTION
**Pull request by burmanm**
**What this PR does**:
Enables golangci-lint and enforces against errors. Also, to pass this PR.. fix all the errors we had.

**Which issue(s) this PR fixes**:
Fixes #325 

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by bradfordcp** [comment]
Is there an issue for this PR?

**Comment by Miles-Garnsey** [comment]
Quick question: with timeouts set to 10 minutes, should we expect all of the tests suites to take 10 minutes longer to enable all the linting? What's the DX impact (if any)?

I think this ticket is a good idea, just wondering if it will delay GHA test runs even more.

**Comment by burmanm** [comment]
I have no idea what "DX impact" is (and neither did Google), so I can't answer to that. And no, this adds max of 10 minutes to the unit testing phase (from history it seems 1 minute at most to that phase), so there's no real impact to the testing phase as the e2e tests are the slower one and they all run in parallel. 

@bradfordcp No ticket, don't think so (could've been in k8ssandra project). This is more of a code quality improvement.

**Comment by Miles-Garnsey** [comment]
> I have no idea what "DX impact" is (and neither did Google), so I can't answer to that. And no, this adds max of 10 minutes to the unit testing phase (from history it seems 1 minute at most to that phase), so there's no real impact to the testing phase as the e2e tests are the slower one and they all run in parallel.
> 
> @bradfordcp No ticket, don't think so (could've been in k8ssandra project). This is more of a code quality improvement.

[DX](https://harness.io/blog/devops/developer-experience/). 

If it is one minute in runtime, this should be a real help. A lot of our commits are a bit dirty due to go fmt/vet making unrelated changes at arbitrary times.

**Comment by burmanm** [comment]
This shouldn't have large amount of impact to developers. On local machine it caches the results, so it takes ~2-3s to run. It's not very strict on checks, mostly those "missing err handling" type of stuff.

Actually, for runtime it's not even going to increase that at all in the GHA. The tests have been done all the time (you can see from the GHA output in some other PRs), but those results haven't been enforced.

**Review by jsanda — APPROVED** [review]
@burmanm can you please can an issue for this? 

Do you think it makes sense to integrate golangci-lint into the Makefile? I think so. If you agree, can you please create a follow up ticket for that as well?

**Comment by burmanm** [comment]
Added makefile target and ticket

**Pull request merged**
