### PR TITLE
Update to ginkgo v2

### LINKED ISSUE #291: K8SSAND-1413 ⁃ Update to ginkgo v2
**What is missing?**
ginkgo v1 is deprecated. We should update tests to ginkgo v2.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1413) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1413
┆priority: Medium

### PR DESCRIPTION
**Pull request by burmanm**
**What this PR does**:
Updates dependency to ginkgo v2, fix controller tests and compilations. Does not use any of the new features in v2.

**Which issue(s) this PR fixes**:
Fixes #291 

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by burmanm** [comment]
@emerkle826 No need to do this part, but you'll want this before starting to modify, otherwise conflicts are going to be quite horrible..

**Comment by emerkle826** [comment]
@thanks @burmanm I was going to look into this as part of my work. I'll keep an eye on this and base my work off of it.

**Comment by burmanm** [comment]
Yeah, I'll just need to find out what imports the v1 also to go.mod, that makes the tests fail..

**Comment by burmanm** [comment]
Yep, the smoke test failure is not the test (the test passed), but something on GHA infra failing to close the test.

**Review by emerkle826 — APPROVED** [review]

**Pull request merged**
